export default function DemoBanner({ provider }: { provider?: string }) {
  return (
    <div
      role="note"
      aria-label="Demo mode notice"
      className="rounded-md border border-amber-300 bg-amber-50 p-4 dark:border-amber-700 dark:bg-amber-950/40"
    >
      <p className="text-sm font-semibold text-amber-900 dark:text-amber-100">
        Demo-generated output — for evaluation only. Review before use.
      </p>
      {provider && (
        <p className="mt-1 text-xs text-amber-800 dark:text-amber-200/80">
          Generated by provider: {provider}
        </p>
      )}
    </div>
  );
}
