"""Generation end-to-end tests against the demo provider."""

from __future__ import annotations

from app.providers.schemas import ASSET_TYPES
from tests.conftest import count_audit, make_project, register

EXPECTED_TYPES = set(ASSET_TYPES)


def _generate(client, project_id: str) -> dict:  # type: ignore[no-untyped-def]
    response = client.post(f"/api/v1/projects/{project_id}/generate", json={})
    assert response.status_code == 200, response.text
    return response.json()


def test_demo_generation_end_to_end(client, db_session) -> None:  # type: ignore[no-untyped-def]
    body = register(client)
    org_id = body["organization"]["id"]
    project = make_project(client)

    generation = _generate(client, project["id"])
    assert generation["status"] == "succeeded"
    assert generation["provider"] == "demo"
    assert generation["error_message"] is None
    assert generation["started_at"] and generation["completed_at"]
    assert count_audit(db_session, "generation.start", org_id) == 1
    assert count_audit(db_session, "generation.success", org_id) == 1

    structured = generation["structured_output"]
    assert structured["summary"]
    assert structured["assumptions"]
    assets = structured["assets"]
    assert assets
    types_present = {a["asset_type"] for a in assets}
    assert EXPECTED_TYPES <= types_present, f"missing: {EXPECTED_TYPES - types_present}"
    for asset in assets:
        assert asset["content"].strip()
        assert (
            "GENERATED BY CLOUDFORGE AI DEMO PROVIDER - review before use"
            in asset["content"]
        )

    # Structured contract validated: zero-trust scores present, findings merged.
    zt = structured["zero_trust"]
    for key in (
        "identity_score",
        "network_score",
        "data_score",
        "workload_score",
        "overall_score",
    ):
        assert 0 <= zt[key] <= 100
    assert structured["security_findings"]
    for finding in structured["security_findings"]:
        assert finding["severity"] in (
            "critical",
            "high",
            "medium",
            "low",
            "informational",
        )
        assert finding["title"] and finding["description"] and finding["recommendation"]

    # Project moved to ready.
    project_now = client.get(f"/api/v1/projects/{project['id']}").json()
    assert project_now["status"] == "ready"


def test_generation_list_and_get(client) -> None:  # type: ignore[no-untyped-def]
    register(client)
    project = make_project(client)
    generation = _generate(client, project["id"])

    listed = client.get(f"/api/v1/projects/{project['id']}/generations").json()
    assert any(g["id"] == generation["id"] for g in listed["items"])

    fetched = client.get(f"/api/v1/generations/{generation['id']}").json()
    assert fetched["id"] == generation["id"]
    assert fetched["status"] == "succeeded"


def test_generation_retry_creates_new(client) -> None:  # type: ignore[no-untyped-def]
    register(client)
    project = make_project(client)
    first = _generate(client, project["id"])

    response = client.post(f"/api/v1/generations/{first['id']}/retry", json={})
    assert response.status_code == 201
    retried = response.json()
    assert retried["id"] != first["id"]
    assert retried["status"] == "succeeded"

    listed = client.get(f"/api/v1/projects/{project['id']}/generations").json()
    assert len(listed["items"]) == 2


def test_generation_tenant_isolation(client, session_factory) -> None:  # type: ignore[no-untyped-def]
    register(client, email="owner2@example.com")
    project = make_project(client)
    generation = _generate(client, project["id"])
    generation_id = generation["id"]

    from fastapi.testclient import TestClient

    from app.database.session import get_db
    from app.main import create_app

    app = create_app()

    def override_get_db():  # type: ignore[no-untyped-def]
        db = session_factory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as other:
        register(other, email="intruder2@example.com", name="Intruder2")
        assert other.get(f"/api/v1/generations/{generation_id}").status_code == 404
        assert (
            other.get(f"/api/v1/generations/{generation_id}/assets").status_code == 404
        )
        assert (
            other.get(f"/api/v1/generations/{generation_id}/export").status_code == 404
        )
    app.dependency_overrides.clear()


def test_invalid_provider_output_rejected(db_session) -> None:  # type: ignore[no-untyped-def]
    """A provider returning schema-invalid output fails the generation cleanly."""
    from app.core.config import get_settings
    from app.models.project import Project
    from app.providers.base import AIProvider
    from app.services.generation_service import run_generation

    class FakeResult:
        def model_dump(self) -> dict:  # type: ignore[no-untyped-def]
            return {"not": "the schema"}

    class BrokenProvider(AIProvider):
        name = "broken"

        def generate(self, request):  # type: ignore[no-untyped-def]
            # Returns an object whose dumped payload cannot validate.
            return FakeResult()  # type: ignore[return-value]

    project = Project(
        organization_id="org-x",
        name="Broken",
        cloud_target="azure",
        environment="development",
        region="eastus",
        availability_requirement="standard",
        compliance_framework="none",
        status="draft",
    )
    db_session.add(project)
    db_session.commit()

    generation = run_generation(
        db_session,
        project=project,
        prompt_override=None,
        settings=get_settings(),
        provider=BrokenProvider(),
    )
    assert generation.status == "failed"
    assert generation.error_message
    assert "validation" in generation.error_message.lower()
    db_session.refresh(project)
    assert project.status == "failed"
