"""Demo AI provider: deterministic, no network.

Builds all 16 asset types from the project parameters (name, cloud target,
environment, region, availability, compliance). Every asset contains the demo
disclaimer line as a comment appropriate to its language.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from app.providers.base import AIProvider
from app.providers.schemas import (
    Architecture,
    ArchitectureComponent,
    CostGuidance,
    GeneratedFile,
    GenerationRequest,
    SecurityFinding,
    StructuredGenerationResult,
    ZeroTrust,
)

DEMO_MODEL = "cloudforge-demo-1.0"
DEMO_DISCLAIMER = "GENERATED BY CLOUDFORGE AI DEMO PROVIDER - review before use"


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug[:48] or "project"


class DemoProvider(AIProvider):
    name = "demo"

    def generate(self, request: GenerationRequest) -> StructuredGenerationResult:
        slug = _slug(request.project_name)
        env = request.environment
        region = request.region
        target = request.cloud_target
        availability = request.availability_requirement
        compliance = request.compliance_framework
        ha = availability in ("high-availability", "multi-region")

        assets = [
            self._terraform(slug, env, region, target, availability, compliance, ha),
            self._bicep(slug, env, region, target, availability, compliance, ha),
            self._arm(slug, env, region, target, availability, compliance, ha),
            self._cloudformation(
                slug, env, region, target, availability, compliance, ha
            ),
            *self._kubernetes(slug, env, region, target, ha),
            *self._helm(slug, env, region, target, ha),
            self._github_actions(slug, env, region, target),
            self._azure_devops(slug, env, region, target),
            self._jenkins(slug, env, region, target),
            self._gitlab_ci(slug, env, region, target),
            self._architecture_doc(slug, env, region, target, availability, compliance),
            self._deployment_doc(slug, env, region, target),
            self._security_doc(slug, env, region, target, compliance),
            self._zero_trust_doc(slug, env, region, target),
            self._cost_doc(slug, env, region, target),
            self._readme(slug, env, region, target, availability, compliance, request),
        ]

        findings = self._security_findings(env, target, ha, compliance)
        zero_trust = self._zero_trust(env, ha)

        prompt_text = (
            request.prompt_override or request.original_prompt or request.description
        )
        summary = (
            f"{request.project_name}: {target} {env} deployment in {region} with "
            f"{availability} availability."
        )
        assumptions = [
            "Demo provider output: all resources are representative templates, not a live design.",
            f"Target region is {region}; adjust for data-residency requirements.",
            f"Environment '{env}' drives SKU choices (dev SKUs are cost-optimized).",
            "Networking assumes a single hub virtual network with three subnets "
            "(app, data, private-endpoint).",
            "Secrets are expected to come from a managed vault or managed identity; "
            "no secrets are embedded in any asset.",
            f"Compliance framework '{compliance}' is treated as readiness guidance, "
            "not certification.",
        ]
        if prompt_text:
            assumptions.append(f"User request summary: {prompt_text[:300]}")

        return StructuredGenerationResult(
            summary=summary,
            assumptions=assumptions,
            architecture=Architecture(
                overview=(
                    f"A {availability} {target} architecture for {request.project_name} "
                    f"running in {region} ({env}). Traffic enters through a private, "
                    "network-controlled front door and fans out to containerized "
                    "workloads backed by managed data services."
                ),
                components=[
                    ArchitectureComponent(
                        name="Virtual network",
                        purpose="Isolated network with app, data, and private-endpoint subnets.",
                    ),
                    ArchitectureComponent(
                        name="Container workloads",
                        purpose="Application services deployed as containers with health probes.",
                    ),
                    ArchitectureComponent(
                        name="Managed data services",
                        purpose="Database and storage reached only via private endpoints.",
                    ),
                    ArchitectureComponent(
                        name="CI/CD pipelines",
                        purpose="Build, scan, and deploy changes with approvals for production.",
                    ),
                    ArchitectureComponent(
                        name="Observability",
                        purpose="Centralized logs and metrics with alerting on key signals.",
                    ),
                ],
                traffic_flow=[
                    "Client -> private front door / ingress (TLS terminated)",
                    "Ingress -> container workloads in the app subnet",
                    "Workloads -> data services over private endpoints (no public internet)",
                    "Pipelines -> workloads via deployment automation with approvals",
                    "All tiers -> centralized logging and metrics",
                ],
            ),
            assets=assets,
            security_findings=findings,
            zero_trust=zero_trust,
            cost_guidance=CostGuidance(
                disclaimer=(
                    "Cost guidance only: figures are not billing estimates. Actual "
                    "charges depend on usage, region pricing, and your agreement. "
                    "Review before use."
                ),
                cost_drivers=[
                    "Compute (container instances / node pools) -- scales with replica count",
                    "Managed database throughput and storage",
                    "Data egress between regions or to the internet",
                    "Log and metrics retention",
                ],
                optimization_recommendations=[
                    "Use dev/test SKUs and auto-shutdown for non-production environments",
                    "Right-size replicas and enable autoscaling on CPU/memory",
                    "Prefer private endpoints over data-egress-heavy public paths",
                    "Set log retention policies aligned with compliance needs",
                ],
            ),
        )

    # ------------------------------------------------------------------ helpers

    def _tags(self, slug: str, env: str) -> dict[str, str]:
        return {
            "project": slug,
            "environment": env,
            "managed-by": "cloudforge-ai",
            "cost-center": "demo",
        }

    def _is_azure(self, target: str) -> bool:
        return target in ("azure", "multi-cloud")

    def _is_aws(self, target: str) -> bool:
        return target in ("aws", "multi-cloud")

    # ------------------------------------------------------------- IaC assets

    def _terraform(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
        ha: bool,
    ) -> GeneratedFile:
        sku_note = "Standard" if env == "production" else "Basic"
        zones = "2" if ha else "1"
        tags = "\n".join(f'    {k} = "{v}"' for k, v in self._tags(slug, env).items())
        azure_block = ""
        if self._is_azure(target):
            azure_block = f"""
resource "azurerm_resource_group" "main" {{
  name     = "rg-{slug}-{env}"
  location = var.region
  tags     = local.tags
}}

resource "azurerm_virtual_network" "main" {{
  name                = "vnet-{slug}-{env}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = ["10.0.0.0/16"]
  tags                = local.tags
}}

resource "azurerm_subnet" "app" {{
  name                 = "snet-app"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}}

resource "azurerm_subnet" "data" {{
  name                 = "snet-data"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
}}

resource "azurerm_subnet" "endpoints" {{
  name                 = "snet-endpoints"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.3.0/24"]
}}

resource "azurerm_network_security_group" "app" {{
  name                = "nsg-{slug}-{env}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.tags
}}

resource "azurerm_log_analytics_workspace" "main" {{
  name                = "log-{slug}-{env}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.tags
}}
"""
        aws_block = ""
        if self._is_aws(target):
            aws_block = f"""
resource "aws_vpc" "main" {{
  cidr_block           = "10.1.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags                 = local.tags
}}

resource "aws_subnet" "app_a" {{
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.1.1.0/24"
  availability_zone = "${{var.region}}a"
  tags              = local.tags
}}

resource "aws_subnet" "app_b" {{
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.1.2.0/24"
  availability_zone = "${{var.region}}b"
  tags              = local.tags
}}

resource "aws_subnet" "data" {{
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.1.3.0/24"
  availability_zone = "${{var.region}}a"
  tags              = local.tags
}}

resource "aws_security_group" "app" {{
  name        = "sg-{slug}-{env}"
  description = "Application tier security group"
  vpc_id      = aws_vpc.main.id
  tags        = local.tags
}}
"""
        content = f"""# {DEMO_DISCLAIMER}
# Terraform for {slug} ({target}, {env}, {region})
# Availability: {availability} | Compliance: {compliance} | Zones: {zones}

terraform {{
  required_version = ">= 1.9.0"
  required_providers {{
    azurerm = {{ source = "hashicorp/azurerm", version = "~> 4.0" }}
    aws     = {{ source = "hashicorp/aws", version = "~> 5.0" }}
  }}
}}

variable "region" {{
  description = "Deployment region"
  type        = string
  default     = "{region}"
}}

locals {{
  tags = {{
{tags}
  }}
  sku_note = "{sku_note}"
}}
{azure_block}{aws_block}
output "deployment_summary" {{
  value = "Deployed {slug} ({target}/{env}) via Terraform"
}}
"""
        return GeneratedFile(
            asset_type="terraform", file_name="main.tf", language="hcl", content=content
        )

    def _bicep(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
        ha: bool,
    ) -> GeneratedFile:
        content = f"""// {DEMO_DISCLAIMER}
// Bicep for {slug} ({target}, {env}, {region})
// Availability: {availability} | Compliance: {compliance}

@description('Deployment location')
param location string = '{region}'

@description('Environment name')
param environment string = '{env}'

@description('High availability enabled')
param highAvailability bool = {'true' if ha else 'false'}

var tags = {{
  project: '{slug}'
  environment: environment
  'managed-by': 'cloudforge-ai'
}}

resource vnet 'Microsoft.Network/virtualNetworks@2024-05-01' = {{
  name: 'vnet-{slug}-${{environment}}'
  location: location
  tags: tags
  properties: {{
    addressSpace: {{ addressPrefixes: ['10.0.0.0/16'] }}
    subnets: [
      {{ name: 'snet-app', properties: {{ addressPrefix: '10.0.1.0/24' }} }}
      {{ name: 'snet-data', properties: {{ addressPrefix: '10.0.2.0/24' }} }}
      {{ name: 'snet-endpoints', properties: {{ addressPrefix: '10.0.3.0/24' }} }}
    ]
  }}
}}

resource nsg 'Microsoft.Network/networkSecurityGroups@2024-05-01' = {{
  name: 'nsg-{slug}-${{environment}}'
  location: location
  tags: tags
  properties: {{
    securityRules: []
  }}
}}

resource workspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {{
  name: 'log-{slug}-${{environment}}'
  location: location
  tags: tags
  properties: {{
    sku: {{ name: 'PerGB2018' }}
    retentionInDays: 30
  }}
}}

output vnetId string = vnet.id
output highAvailabilityEnabled bool = highAvailability
"""
        return GeneratedFile(
            asset_type="bicep",
            file_name="main.bicep",
            language="bicep",
            content=content,
        )

    def _arm(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
        ha: bool,
    ) -> GeneratedFile:
        template = {
            "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
            "contentVersion": "1.0.0.0",
            "_comment": DEMO_DISCLAIMER,
            "metadata": {
                "description": f"ARM template for {slug} ({target}, {env}, {region})",
                "availability": availability,
                "compliance": compliance,
            },
            "parameters": {
                "location": {"type": "string", "defaultValue": region},
                "environment": {"type": "string", "defaultValue": env},
            },
            "variables": {
                "vnetName": f"vnet-{slug}-{env}",
                "nsgName": f"nsg-{slug}-{env}",
                "tags": {
                    "project": slug,
                    "environment": env,
                    "managed-by": "cloudforge-ai",
                },
            },
            "resources": [
                {
                    "type": "Microsoft.Network/virtualNetworks",
                    "apiVersion": "2024-05-01",
                    "name": "[variables('vnetName')]",
                    "location": "[parameters('location')]",
                    "tags": "[variables('tags')]",
                    "properties": {
                        "addressSpace": {"addressPrefixes": ["10.0.0.0/16"]},
                        "subnets": [
                            {
                                "name": "snet-app",
                                "properties": {"addressPrefix": "10.0.1.0/24"},
                            },
                            {
                                "name": "snet-data",
                                "properties": {"addressPrefix": "10.0.2.0/24"},
                            },
                            {
                                "name": "snet-endpoints",
                                "properties": {"addressPrefix": "10.0.3.0/24"},
                            },
                        ],
                    },
                },
                {
                    "type": "Microsoft.Network/networkSecurityGroups",
                    "apiVersion": "2024-05-01",
                    "name": "[variables('nsgName')]",
                    "location": "[parameters('location')]",
                    "tags": "[variables('tags')]",
                    "properties": {"securityRules": []},
                },
            ],
            "outputs": {
                "vnetId": {
                    "type": "string",
                    "value": "[resourceId('Microsoft.Network/virtualNetworks', variables('vnetName'))]",
                },
                "highAvailability": {"type": "bool", "value": ha},
            },
        }
        return GeneratedFile(
            asset_type="arm",
            file_name="main.json",
            language="json",
            content=json.dumps(template, indent=2) + "\n",
        )

    def _cloudformation(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
        ha: bool,
    ) -> GeneratedFile:
        content = f"""# {DEMO_DISCLAIMER}
# CloudFormation for {slug} ({target}, {env}, {region})
# Availability: {availability} | Compliance: {compliance}
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template for {slug} ({env}) - VPC with 3 subnets,
  security groups, and flow logging.

Parameters:
  Environment:
    Type: String
    Default: {env}
    AllowedValues: [development, test, production]

Mappings:
  NetworkConfig:
    Defaults:
      VpcCidr: 10.1.0.0/16
      AppSubnetA: 10.1.1.0/24
      AppSubnetB: 10.1.2.0/24
      DataSubnet: 10.1.3.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [NetworkConfig, Defaults, VpcCidr]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: project
          Value: {slug}
        - Key: environment
          Value: !Ref Environment
        - Key: managed-by
          Value: cloudforge-ai

  AppSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [NetworkConfig, Defaults, AppSubnetA]
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '{slug}-${{Environment}}-app-a'

  AppSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [NetworkConfig, Defaults, AppSubnetB]
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '{slug}-${{Environment}}-app-b'

  DataSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [NetworkConfig, Defaults, DataSubnet]
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '{slug}-${{Environment}}-data'

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Application tier security group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.1.0.0/16
      Tags:
        - Key: project
          Value: {slug}

  FlowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/{slug}/${{Environment}}/vpc-flow-logs'
      RetentionInDays: 30

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
  HighAvailability:
    Description: Whether multi-AZ subnets were provisioned
    Value: '{str(ha).lower()}'
"""
        return GeneratedFile(
            asset_type="cloudformation",
            file_name="template.yaml",
            language="yaml",
            content=content,
        )

    def _kubernetes(
        self, slug: str, env: str, region: str, target: str, ha: bool
    ) -> list[GeneratedFile]:
        replicas = 3 if ha or env == "production" else 2
        deployment = f"""# {DEMO_DISCLAIMER}
# Kubernetes Deployment for {slug} ({target}, {env}, {region})
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {slug}
  namespace: {slug}-{env}
  labels:
    app.kubernetes.io/name: {slug}
    app.kubernetes.io/managed-by: cloudforge-ai
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app.kubernetes.io/name: {slug}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {slug}
    spec:
      serviceAccountName: {slug}-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: ghcr.io/example/{slug}:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "{env}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
"""
        service = f"""# {DEMO_DISCLAIMER}
# Kubernetes Service for {slug} ({target}, {env}, {region})
apiVersion: v1
kind: Service
metadata:
  name: {slug}
  namespace: {slug}-{env}
  labels:
    app.kubernetes.io/name: {slug}
    app.kubernetes.io/managed-by: cloudforge-ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {slug}
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {slug}-sa
  namespace: {slug}-{env}
automountServiceAccountToken: false
"""
        return [
            GeneratedFile(
                asset_type="kubernetes",
                file_name="deployment.yaml",
                language="yaml",
                content=deployment,
            ),
            GeneratedFile(
                asset_type="kubernetes",
                file_name="service.yaml",
                language="yaml",
                content=service,
            ),
        ]

    def _helm(
        self, slug: str, env: str, region: str, target: str, ha: bool
    ) -> list[GeneratedFile]:
        chart = f"""# {DEMO_DISCLAIMER}
apiVersion: v2
name: {slug}
description: Helm chart for {slug} ({target}, {env}, {region})
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - cloudforge-ai
maintainers:
  - name: cloudforge-ai
"""
        values = f"""# {DEMO_DISCLAIMER}
# Default values for {slug}.
replicaCount: {3 if ha or env == "production" else 2}

image:
  repository: ghcr.io/example/{slug}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

environment: {env}
region: {region}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

security:
  runAsNonRoot: true

probes:
  livenessPath: /health
  readinessPath: /ready
"""
        template = f"""# {DEMO_DISCLAIMER}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{{ .Release.Name }}}}
  labels:
    app.kubernetes.io/name: {slug}
    app.kubernetes.io/managed-by: cloudforge-ai
spec:
  replicas: {{{{ .Values.replicaCount }}}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {slug}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {slug}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{{{ .Values.image.repository }}}}{{{{ .Values.image.tag }}}}"
          imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
          ports:
            - name: http
              containerPort: 8080
          resources: {{{{ toYaml .Values.resources | nindent 12 }}}}
          livenessProbe:
            httpGet:
              path: {{{{ .Values.probes.livenessPath }}}}
              port: http
          readinessProbe:
            httpGet:
              path: {{{{ .Values.probes.readinessPath }}}}
              port: http
"""
        return [
            GeneratedFile(
                asset_type="helm",
                file_name="Chart.yaml",
                language="yaml",
                content=chart,
            ),
            GeneratedFile(
                asset_type="helm",
                file_name="values.yaml",
                language="yaml",
                content=values,
            ),
            GeneratedFile(
                asset_type="helm",
                file_name="templates/deployment.yaml",
                language="yaml",
                content=template,
            ),
        ]

    # ------------------------------------------------------------ pipeline assets

    def _github_actions(
        self, slug: str, env: str, region: str, target: str
    ) -> GeneratedFile:
        content = f"""# {DEMO_DISCLAIMER}
# GitHub Actions CI/CD for {slug} ({target}, {env}, {region})
name: ci-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_SLUG: {slug}
  REGION: {region}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Lint
        run: |
          pip install ruff
          ruff check .
          ruff format --check .
      - name: Unit tests
        run: |
          pip install -r backend/requirements.txt
          pytest backend/tests -q

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: {env}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (placeholder for {target} deployment)
        run: echo "Deploying ${{{{ env.PROJECT_SLUG }}}} to {target} {region}"
"""
        return GeneratedFile(
            asset_type="github-actions",
            file_name="ci-deploy.yml",
            language="yaml",
            content=content,
        )

    def _azure_devops(
        self, slug: str, env: str, region: str, target: str
    ) -> GeneratedFile:
        content = f"""# {DEMO_DISCLAIMER}
# Azure DevOps pipeline for {slug} ({target}, {env}, {region})
trigger:
  branches:
    include:
      - main

variables:
  projectSlug: {slug}
  region: {region}
  environment: {env}

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
          - script: |
              pip install ruff
              ruff check .
              ruff format --check .
            displayName: Lint
          - script: |
              pip install -r backend/requirements.txt
              pytest backend/tests -q
            displayName: Unit tests

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Deploy
        environment: {env}
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying $(projectSlug) to {target} $(region)"
                  displayName: Deploy
"""
        return GeneratedFile(
            asset_type="azure-devops",
            file_name="azure-pipelines.yml",
            language="yaml",
            content=content,
        )

    def _jenkins(self, slug: str, env: str, region: str, target: str) -> GeneratedFile:
        content = f"""// {DEMO_DISCLAIMER}
// Jenkins pipeline for {slug} ({target}, {env}, {region})
pipeline {{
  agent any

  environment {{
    PROJECT_SLUG = '{slug}'
    REGION = '{region}'
    ENVIRONMENT = '{env}'
  }}

  stages {{
    stage('Checkout') {{
      steps {{ checkout scm }}
    }}
    stage('Lint') {{
      steps {{
        sh 'pip install ruff && ruff check . && ruff format --check .'
      }}
    }}
    stage('Test') {{
      steps {{
        sh 'pip install -r backend/requirements.txt && pytest backend/tests -q'
      }}
    }}
    stage('Deploy') {{
      when {{ branch 'main' }}
      steps {{
        echo "Deploying ${{env.PROJECT_SLUG}} to {target} ${{env.REGION}}"
      }}
    }}
  }}

  post {{
    always {{ cleanWs() }}
  }}
}}
"""
        return GeneratedFile(
            asset_type="jenkins",
            file_name="Jenkinsfile",
            language="groovy",
            content=content,
        )

    def _gitlab_ci(
        self, slug: str, env: str, region: str, target: str
    ) -> GeneratedFile:
        content = f"""# {DEMO_DISCLAIMER}
# GitLab CI for {slug} ({target}, {env}, {region})
stages:
  - lint
  - test
  - deploy

variables:
  PROJECT_SLUG: {slug}
  REGION: {region}

lint:
  stage: lint
  image: python:3.12-slim
  script:
    - pip install ruff
    - ruff check .
    - ruff format --check .

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -r backend/requirements.txt
    - pytest backend/tests -q

deploy:
  stage: deploy
  image: python:3.12-slim
  environment:
    name: {env}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Deploying $PROJECT_SLUG to {target} $REGION"
"""
        return GeneratedFile(
            asset_type="gitlab-ci",
            file_name=".gitlab-ci.yml",
            language="yaml",
            content=content,
        )

    # --------------------------------------------------------------- doc assets

    def _architecture_doc(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
    ) -> GeneratedFile:
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# Architecture: {slug}

- **Cloud target:** {target}
- **Environment:** {env}
- **Region:** {region}
- **Availability:** {availability}
- **Compliance framework:** {compliance}

## Overview

{slug} is deployed as a containerized workload on {target} in {region}.
The design favors private networking, managed identities, and least-privilege
access. State lives in managed data services reached only through private
endpoints.

## Components

| Component | Purpose |
|-----------|---------|
| Virtual network | Isolated network with app, data, and private-endpoint subnets |
| Container workloads | Application services with health probes and resource limits |
| Managed data services | Database and storage behind private endpoints |
| CI/CD pipelines | Build, scan, and deploy with approvals for production |
| Observability | Centralized logs/metrics with alerting |

## Traffic flow

1. Client -> private ingress (TLS terminated at the edge)
2. Ingress -> container workloads in the app subnet
3. Workloads -> data services over private endpoints (no public internet path)
4. Pipelines -> workloads via deployment automation with approvals
5. All tiers -> centralized logging and metrics

## Decisions and trade-offs

- Private endpoints add cost but remove public data-plane exposure.
- Multi-subnet layout keeps blast radius small if a tier is compromised.
- Demo output: validate instance SKUs and zone redundancy against real demand.
"""
        return GeneratedFile(
            asset_type="architecture",
            file_name="ARCHITECTURE.md",
            language="markdown",
            content=content,
        )

    def _deployment_doc(
        self, slug: str, env: str, region: str, target: str
    ) -> GeneratedFile:
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# Deployment guide: {slug}

Target: **{target}** | Environment: **{env}** | Region: **{region}**

## Prerequisites

- Access to the {target} subscription/account for {region}
- Terraform >= 1.9.0 (or the IaC tool of your choice from this package)
- A container registry you control
- A secrets vault (do not commit secrets to this repo)

## Steps

1. Review every generated file. This is demo output -- adapt names, SKUs,
   and network ranges to your organization.
2. Create the vault entries and managed identities your workloads need.
3. Initialize and plan the infrastructure:
   ```bash
   terraform init
   terraform plan -out plan.out
   ```
4. Apply after reviewing the plan:
   ```bash
   terraform apply plan.out
   ```
5. Build and push the container image, then deploy with Helm or kubectl:
   ```bash
   helm upgrade --install {slug} ./helm -f ./helm/values.yaml
   ```
6. Verify health endpoints (`/health`, `/ready`) and check centralized logs.

## Rollback

- Keep the previous container image tagged; `helm rollback` restores it.
- Infrastructure changes should be reverted with a reviewed `terraform plan`.
"""
        return GeneratedFile(
            asset_type="deployment",
            file_name="DEPLOYMENT.md",
            language="markdown",
            content=content,
        )

    def _security_doc(
        self, slug: str, env: str, region: str, target: str, compliance: str
    ) -> GeneratedFile:
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# Security guidance: {slug}

> Automated guidance, not a formal security audit.

Target: **{target}** | Environment: **{env}** | Region: **{region}** |
Compliance: **{compliance}**

## Baseline controls in this package

- Private networking: app, data, and private-endpoint subnets; no public ingress by default
- Managed identities and least-privilege role assignments
- Network security groups / security groups with default-deny posture
- Centralized diagnostics (30-day retention; extend for {compliance} if required)
- Containers run as non-root with read-only filesystems and dropped capabilities
- Health probes so unhealthy workloads are replaced, not served

## Before production

1. Enable private endpoints for every data service.
2. Turn on encryption at rest with customer-managed keys where {compliance} requires it.
3. Add backup and point-in-time restore for stateful services.
4. Add container image scanning and sign images in the pipeline.
5. Review IAM: no wildcard actions, no world-open ingress except where explicitly justified.
6. Extend log retention to meet {compliance} evidence requirements.

## Compliance note

Compliance framework '{compliance}' is treated as readiness guidance here, not
certification. A qualified assessor must validate any formal claim.
"""
        return GeneratedFile(
            asset_type="security",
            file_name="SECURITY.md",
            language="markdown",
            content=content,
        )

    def _zero_trust_doc(
        self, slug: str, env: str, region: str, target: str
    ) -> GeneratedFile:
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# Zero-trust guidance: {slug}

> Automated guidance, not a formal security audit.

Target: **{target}** | Environment: **{env}** | Region: **{region}**

## Pillars

- **Identity:** workloads use managed identities; humans authenticate with MFA
  and short-lived credentials. No long-lived secrets in code or pipelines.
- **Network:** micro-segmented subnets, default-deny NSGs, private endpoints
  for data services. Assume breach: every hop is authenticated.
- **Data:** encryption in transit (TLS) and at rest; classification of
  sensitive fields; access logged.
- **Workload:** hardened container images, non-root execution, admission
  policies, image scanning in CI.

## Recommendations

1. Enforce MFA and conditional access for all human access.
2. Give each workload its own identity with least-privilege roles.
3. Deny all inter-subnet traffic by default; allow-list explicitly.
4. Scan and sign container images; block unsigned images at deploy time.
5. Encrypt backups and test restores regularly.
"""
        return GeneratedFile(
            asset_type="zero-trust",
            file_name="ZERO_TRUST.md",
            language="markdown",
            content=content,
        )

    def _cost_doc(self, slug: str, env: str, region: str, target: str) -> GeneratedFile:
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# Cost guidance: {slug}

> Cost guidance only: figures are not billing estimates. Actual charges depend
> on usage, region pricing, and your agreement.

Target: **{target}** | Environment: **{env}** | Region: **{region}**

## Main cost drivers

- Compute (container instances / node pools) -- scales with replica count
- Managed database throughput and storage
- Data egress between regions or to the internet
- Log and metrics retention

## Optimization recommendations

- Use dev/test SKUs and auto-shutdown for non-production environments
- Right-size replicas and enable autoscaling on CPU/memory
- Prefer private endpoints over data-egress-heavy public paths
- Set log retention policies aligned with compliance needs
- Tag everything (`project`, `environment`, `cost-center`) so spend is attributable
"""
        return GeneratedFile(
            asset_type="cost", file_name="COST.md", language="markdown", content=content
        )

    def _readme(
        self,
        slug: str,
        env: str,
        region: str,
        target: str,
        availability: str,
        compliance: str,
        request: GenerationRequest,
    ) -> GeneratedFile:
        generated_at = datetime.now(timezone.utc).isoformat()
        content = f"""<!-- {DEMO_DISCLAIMER} -->
# {request.project_name}

Cloud project generated by **CloudForge AI** (demo provider) on {generated_at}.

- **Cloud target:** {target}
- **Environment:** {env}
- **Region:** {region}
- **Availability:** {availability}
- **Compliance:** {compliance}

## Contents

| Directory / file | Description |
|------------------|-------------|
| `terraform/` | Terraform configuration (`main.tf`) |
| `bicep/` | Bicep template (`main.bicep`) |
| `arm/` | ARM template (`main.json`) |
| `cloudformation/` | CloudFormation template (`template.yaml`) |
| `kubernetes/` | Kubernetes manifests |
| `helm/` | Helm chart |
| `pipelines/` | CI/CD pipelines (GitHub Actions, Azure DevOps, Jenkins, GitLab CI) |
| `docs/` | Architecture and deployment guides |
| `security/` | Security and zero-trust guidance |

## Getting started

1. Read `docs/ARCHITECTURE.md` and `docs/DEPLOYMENT.md`.
2. Review the IaC for your target platform and adapt it.
3. Configure your secrets vault -- never commit secrets.
4. Deploy via your chosen pipeline.

> {DEMO_DISCLAIMER}
"""
        return GeneratedFile(
            asset_type="readme",
            file_name="README.md",
            language="markdown",
            content=content,
        )

    # ------------------------------------------------- structured sub-sections

    def _security_findings(
        self, env: str, target: str, ha: bool, compliance: str
    ) -> list[SecurityFinding]:
        findings = [
            SecurityFinding(
                severity="medium",
                title="Review default NSG rule set before production",
                description=(
                    "The generated network security groups ship with an empty "
                    "rule set. Explicit allow rules must be added and reviewed."
                ),
                recommendation="Define explicit allow rules per tier and keep a default-deny posture.",
            ),
            SecurityFinding(
                severity="informational",
                title="Demo output requires human review",
                description=(
                    "All assets were generated by the CloudForge AI demo provider "
                    "and have not been validated against a live environment."
                ),
                recommendation="Have a cloud architect review and adapt every file before use.",
            ),
        ]
        if env == "production":
            findings.append(
                SecurityFinding(
                    severity="high",
                    title="Enable private endpoints for production data services",
                    description=(
                        "Production data planes must not be reachable over public "
                        "endpoints."
                    ),
                    recommendation="Provision private endpoints and disable public network access.",
                )
            )
        if not ha:
            findings.append(
                SecurityFinding(
                    severity="medium",
                    title="Single-zone footprint",
                    description="The deployment is not spread across multiple zones.",
                    recommendation="Enable zone redundancy for production availability targets.",
                )
            )
        if compliance != "none":
            findings.append(
                SecurityFinding(
                    severity="low",
                    title=f"Compliance readiness for {compliance}",
                    description=(
                        f"Readiness guidance for {compliance} is included, but this "
                        "is not a certification."
                    ),
                    recommendation="Engage a qualified assessor for formal compliance validation.",
                )
            )
        return findings

    def _zero_trust(self, env: str, ha: bool) -> ZeroTrust:
        identity = 85
        network = 80 if env == "production" else 70
        data = 75
        workload = 80
        overall = round((identity + network + data + workload) / 4)
        return ZeroTrust(
            identity_score=identity,
            network_score=network,
            data_score=data,
            workload_score=workload,
            overall_score=overall,
            recommendations=[
                "Enforce MFA and conditional access for all human access.",
                "Give each workload its own managed identity with least-privilege roles.",
                "Deny inter-subnet traffic by default; allow-list explicitly.",
                "Scan and sign container images; block unsigned images at deploy time.",
            ],
        )
